// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservationService.Data;

#nullable disable

namespace ReservationService.Migrations
{
    [DbContext(typeof(ReservationDbContext))]
    partial class ReservationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReservationService.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ReservationService.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClosingHour")
                        .HasColumnType("text");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OpeningHour")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StreetName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "BranchName")
                        .IsUnique();

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchName = "Oddział główny",
                            City = "Warszawa",
                            CompanyId = 1,
                            Country = "Polska",
                            CreatedAt = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4485),
                            PostalCode = "00-001",
                            StreetName = "ul. Główna 15"
                        },
                        new
                        {
                            Id = 2,
                            BranchName = "Oddział główny",
                            City = "Warszawa",
                            CompanyId = 2,
                            Country = "Polska",
                            CreatedAt = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4487),
                            PostalCode = "00-120",
                            StreetName = "ul. Męska 10"
                        },
                        new
                        {
                            Id = 3,
                            BranchName = "Oddział główny",
                            City = "Kraków",
                            CompanyId = 3,
                            Country = "Polska",
                            CreatedAt = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4488),
                            PostalCode = "30-001",
                            StreetName = "ul. Piękna 5"
                        },
                        new
                        {
                            Id = 4,
                            BranchName = "Oddział główny",
                            City = "Kraków",
                            CompanyId = 4,
                            Country = "Polska",
                            CreatedAt = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4489),
                            PostalCode = "30-045",
                            StreetName = "ul. Leśna 8"
                        },
                        new
                        {
                            Id = 5,
                            BranchName = "Oddział główny",
                            City = "Wrocław",
                            CompanyId = 5,
                            Country = "Polska",
                            CreatedAt = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4490),
                            PostalCode = "50-001",
                            StreetName = "ul. Dłonie 2"
                        },
                        new
                        {
                            Id = 6,
                            BranchName = "Oddział główny",
                            City = "Poznań",
                            CompanyId = 6,
                            Country = "Polska",
                            CreatedAt = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4492),
                            PostalCode = "60-001",
                            StreetName = "ul. Relaksu 21"
                        },
                        new
                        {
                            Id = 7,
                            BranchName = "Oddział główny",
                            City = "Wrocław",
                            CompanyId = 7,
                            Country = "Polska",
                            CreatedAt = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4493),
                            PostalCode = "50-120",
                            StreetName = "ul. Kawowa 7"
                        },
                        new
                        {
                            Id = 8,
                            BranchName = "Oddział główny",
                            City = "Gdańsk",
                            CompanyId = 8,
                            Country = "Polska",
                            CreatedAt = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4494),
                            PostalCode = "80-001",
                            StreetName = "ul. Luksusowa 1"
                        },
                        new
                        {
                            Id = 9,
                            BranchName = "Oddział główny",
                            City = "Łódź",
                            CompanyId = 9,
                            Country = "Polska",
                            CreatedAt = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4495),
                            PostalCode = "90-001",
                            StreetName = "ul. Miejska 11"
                        },
                        new
                        {
                            Id = 11,
                            BranchName = "Oddział główny",
                            City = "Rzeszów",
                            CompanyId = 11,
                            Country = "Polska",
                            CreatedAt = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4497),
                            PostalCode = "35-001",
                            StreetName = "ul. Rzeszowska 14"
                        },
                        new
                        {
                            Id = 12,
                            BranchName = "Oddział główny",
                            City = "Rzeszów",
                            CompanyId = 12,
                            Country = "Polska",
                            CreatedAt = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4499),
                            PostalCode = "35-010",
                            StreetName = "ul. Piłsudskiego 22"
                        });
                });

            modelBuilder.Entity("ReservationService.Models.BranchReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId", "BranchId", "CreatedAt");

                    b.ToTable("BranchReviews");
                });

            modelBuilder.Entity("ReservationService.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClosingHour")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OpeningHour")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StreetName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Warszawa",
                            CompanyName = "Artistic Studio",
                            Country = "Polska",
                            Description = "Nowoczesny salon fryzjerski z wieloletnim doświadczeniem",
                            Email = "kontakt@artisticstudio.pl",
                            Phone = "123456789",
                            PostalCode = "00-001",
                            RegistrationDate = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4187),
                            StreetName = "ul. Główna 15",
                            Website = "https://artisticstudio.pl"
                        },
                        new
                        {
                            Id = 2,
                            City = "Warszawa",
                            CompanyName = "Barber Craft",
                            Country = "Polska",
                            Description = "Męski barber shop z tradycyjnym podejściem do stylizacji",
                            Email = "kontakt@barbercraft.pl",
                            Phone = "222333444",
                            PostalCode = "00-120",
                            RegistrationDate = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4190),
                            StreetName = "ul. Męska 10",
                            Website = "https://barbercraft.pl"
                        },
                        new
                        {
                            Id = 3,
                            City = "Kraków",
                            CompanyName = "Beauty Glamour",
                            Country = "Polska",
                            Description = "Profesjonalne studio urody i kosmetyki",
                            Email = "kontakt@beautyglamour.pl",
                            Phone = "333444555",
                            PostalCode = "30-001",
                            RegistrationDate = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4192),
                            StreetName = "ul. Piękna 5",
                            Website = "https://beautyglamour.pl"
                        },
                        new
                        {
                            Id = 4,
                            City = "Kraków",
                            CompanyName = "Wellness Spa",
                            Country = "Polska",
                            Description = "Centrum SPA i masażu relaksacyjnego",
                            Email = "info@wellnessspa.pl",
                            Phone = "444555666",
                            PostalCode = "30-045",
                            RegistrationDate = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4194),
                            StreetName = "ul. Leśna 8",
                            Website = "https://wellnessspa.pl"
                        },
                        new
                        {
                            Id = 5,
                            City = "Wrocław",
                            CompanyName = "Nails Studio",
                            Country = "Polska",
                            Description = "Profesjonalny salon paznokci i stylizacji dłoni",
                            Email = "kontakt@nailsstudio.pl",
                            Phone = "555666777",
                            PostalCode = "50-001",
                            RegistrationDate = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4196),
                            StreetName = "ul. Dłonie 2",
                            Website = "https://nailsstudio.pl"
                        },
                        new
                        {
                            Id = 6,
                            City = "Poznań",
                            CompanyName = "Massage Center",
                            Country = "Polska",
                            Description = "Masaże relaksacyjne i zabiegi lecznicze",
                            Email = "kontakt@massagecenter.pl",
                            Phone = "666777888",
                            PostalCode = "60-001",
                            RegistrationDate = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4198),
                            StreetName = "ul. Relaksu 21",
                            Website = "https://massagecenter.pl"
                        },
                        new
                        {
                            Id = 7,
                            City = "Wrocław",
                            CompanyName = "Coffee Barber",
                            Country = "Polska",
                            Description = "Barber shop z kawiarnią w stylu industrialnym",
                            Email = "kontakt@coffeebarber.pl",
                            Phone = "777888999",
                            PostalCode = "50-120",
                            RegistrationDate = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4200),
                            StreetName = "ul. Kawowa 7",
                            Website = "https://coffeebarber.pl"
                        },
                        new
                        {
                            Id = 8,
                            City = "Gdańsk",
                            CompanyName = "Prestige Clinic",
                            Country = "Polska",
                            Description = "Zaawansowane zabiegi kosmetologiczne i medycyny estetycznej",
                            Email = "rejestracja@prestigeclinic.pl",
                            Phone = "888999000",
                            PostalCode = "80-001",
                            RegistrationDate = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4201),
                            StreetName = "ul. Luksusowa 1",
                            Website = "https://prestigeclinic.pl"
                        },
                        new
                        {
                            Id = 9,
                            City = "Łódź",
                            CompanyName = "City Hair Studio",
                            Country = "Polska",
                            Description = "Nowoczesny salon fryzjerski w centrum miasta",
                            Email = "kontakt@cityhairstudio.pl",
                            Phone = "999000111",
                            PostalCode = "90-001",
                            RegistrationDate = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4203),
                            StreetName = "ul. Miejska 11",
                            Website = "https://cityhairstudio.pl"
                        },
                        new
                        {
                            Id = 11,
                            City = "Rzeszów",
                            CompanyName = "Podkarpackie Barber Shop",
                            Country = "Polska",
                            Description = "Tradycyjny barber shop z nowoczesnym podejściem",
                            Email = "kontakt@podkarpackiebarber.pl",
                            Phone = "171234567",
                            PostalCode = "35-001",
                            RegistrationDate = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4205),
                            StreetName = "ul. Rzeszowska 14",
                            Website = "https://podkarpackiebarber.pl"
                        },
                        new
                        {
                            Id = 12,
                            City = "Rzeszów",
                            CompanyName = "Beauty Studio Rzeszów",
                            Country = "Polska",
                            Description = "Nowoczesne studio urody z pełną ofertą zabiegów",
                            Email = "info@beautystudiorzeszow.pl",
                            Phone = "172345678",
                            PostalCode = "35-010",
                            RegistrationDate = new DateTime(2025, 12, 30, 9, 39, 19, 675, DateTimeKind.Utc).AddTicks(4207),
                            StreetName = "ul. Piłsudskiego 22",
                            Website = "https://beautystudiorzeszow.pl"
                        });
                });

            modelBuilder.Entity("ReservationService.Models.EventStore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("OccurredAt");

                    b.ToTable("EventStores");
                });

            modelBuilder.Entity("ReservationService.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("StaffId")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("CompanyId", "BranchId", "ServiceId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("ReservationService.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            CompanyId = 1,
                            Description = "Klasyczne strzyżenie męskie",
                            DurationMinutes = 30,
                            Price = 50m,
                            ServiceName = "Strzyżenie męskie"
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            CompanyId = 1,
                            Description = "Strzyżenie i modelowanie",
                            DurationMinutes = 60,
                            Price = 80m,
                            ServiceName = "Strzyżenie damskie"
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 1,
                            CompanyId = 1,
                            Description = "Stylizacja włosów na specjalne okazje",
                            DurationMinutes = 45,
                            Price = 70m,
                            ServiceName = "Modelowanie włosów"
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 1,
                            CompanyId = 1,
                            Description = "Farbowanie włosów z konsultacją",
                            DurationMinutes = 120,
                            Price = 200m,
                            ServiceName = "Koloryzacja"
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 1,
                            CompanyId = 1,
                            Description = "Zabieg odbudowujący strukturę włosa",
                            DurationMinutes = 90,
                            Price = 150m,
                            ServiceName = "Regeneracja włosów"
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 2,
                            CompanyId = 2,
                            Description = "Modelowanie i pielęgnacja brody",
                            DurationMinutes = 30,
                            Price = 60m,
                            ServiceName = "Strzyżenie brody"
                        },
                        new
                        {
                            Id = 7,
                            BranchId = 2,
                            CompanyId = 2,
                            Description = "Strzyżenie z myciem i stylizacją",
                            DurationMinutes = 45,
                            Price = 90m,
                            ServiceName = "Strzyżenie męskie premium"
                        },
                        new
                        {
                            Id = 8,
                            BranchId = 2,
                            CompanyId = 2,
                            Description = "Kompleksowa pielęgnacja brody i włosów",
                            DurationMinutes = 60,
                            Price = 120m,
                            ServiceName = "Pakiet broda + włosy"
                        },
                        new
                        {
                            Id = 9,
                            BranchId = 2,
                            CompanyId = 2,
                            Description = "Tradycyjne golenie brzytwą",
                            DurationMinutes = 40,
                            Price = 70m,
                            ServiceName = "Golenie brzytwą"
                        },
                        new
                        {
                            Id = 10,
                            BranchId = 2,
                            CompanyId = 2,
                            Description = "Strzyżenie dziecięce",
                            DurationMinutes = 30,
                            Price = 45m,
                            ServiceName = "Strzyżenie dla chłopców"
                        },
                        new
                        {
                            Id = 11,
                            BranchId = 3,
                            CompanyId = 3,
                            Description = "Manicure z malowaniem paznokci",
                            DurationMinutes = 60,
                            Price = 80m,
                            ServiceName = "Manicure klasyczny"
                        },
                        new
                        {
                            Id = 12,
                            BranchId = 3,
                            CompanyId = 3,
                            Description = "Pedicure z masażem stóp",
                            DurationMinutes = 75,
                            Price = 120m,
                            ServiceName = "Pedicure spa"
                        },
                        new
                        {
                            Id = 13,
                            BranchId = 3,
                            CompanyId = 3,
                            Description = "Makijaż na specjalne okazje",
                            DurationMinutes = 60,
                            Price = 150m,
                            ServiceName = "Makijaż okolicznościowy"
                        },
                        new
                        {
                            Id = 14,
                            BranchId = 3,
                            CompanyId = 3,
                            Description = "Indywidualnie dobrany zabieg pielęgnacyjny",
                            DurationMinutes = 90,
                            Price = 200m,
                            ServiceName = "Zabieg na twarz"
                        },
                        new
                        {
                            Id = 15,
                            BranchId = 3,
                            CompanyId = 3,
                            Description = "Podkreślenie oprawy oczu",
                            DurationMinutes = 30,
                            Price = 60m,
                            ServiceName = "Henna brwi i rzęs"
                        },
                        new
                        {
                            Id = 16,
                            BranchId = 4,
                            CompanyId = 4,
                            Description = "Całościowy masaż relaksacyjny",
                            DurationMinutes = 60,
                            Price = 180m,
                            ServiceName = "Masaż relaksacyjny"
                        },
                        new
                        {
                            Id = 17,
                            BranchId = 4,
                            CompanyId = 4,
                            Description = "Masaż z użyciem gorących kamieni",
                            DurationMinutes = 75,
                            Price = 220m,
                            ServiceName = "Masaż gorącymi kamieniami"
                        },
                        new
                        {
                            Id = 18,
                            BranchId = 4,
                            CompanyId = 4,
                            Description = "Pakiet sauna i masaż",
                            DurationMinutes = 90,
                            Price = 250m,
                            ServiceName = "Sauna + masaż"
                        },
                        new
                        {
                            Id = 19,
                            BranchId = 4,
                            CompanyId = 4,
                            Description = "Pakiet spa dla dwóch osób",
                            DurationMinutes = 120,
                            Price = 400m,
                            ServiceName = "Rytuał spa dla dwojga"
                        },
                        new
                        {
                            Id = 20,
                            BranchId = 4,
                            CompanyId = 4,
                            Description = "Masaż pleców i karku",
                            DurationMinutes = 45,
                            Price = 120m,
                            ServiceName = "Masaż pleców"
                        },
                        new
                        {
                            Id = 21,
                            BranchId = 5,
                            CompanyId = 5,
                            Description = "Manicure z lakierem hybrydowym",
                            DurationMinutes = 75,
                            Price = 100m,
                            ServiceName = "Manicure hybrydowy"
                        },
                        new
                        {
                            Id = 22,
                            BranchId = 5,
                            CompanyId = 5,
                            Description = "Uzupełnianie paznokci żelowych",
                            DurationMinutes = 90,
                            Price = 130m,
                            ServiceName = "Uzupełnianie żelu"
                        },
                        new
                        {
                            Id = 23,
                            BranchId = 5,
                            CompanyId = 5,
                            Description = "Podstawowa pielęgnacja stóp",
                            DurationMinutes = 60,
                            Price = 90m,
                            ServiceName = "Pedicure klasyczny"
                        },
                        new
                        {
                            Id = 24,
                            BranchId = 5,
                            CompanyId = 5,
                            Description = "Pielęgnacja paznokci japońską metodą",
                            DurationMinutes = 60,
                            Price = 110m,
                            ServiceName = "Manicure japoński"
                        },
                        new
                        {
                            Id = 25,
                            BranchId = 5,
                            CompanyId = 5,
                            Description = "Artystyczne zdobienia paznokci",
                            DurationMinutes = 45,
                            Price = 60m,
                            ServiceName = "Zdobienie paznokci"
                        },
                        new
                        {
                            Id = 26,
                            BranchId = 6,
                            CompanyId = 6,
                            Description = "Masaż klasyczny całego ciała",
                            DurationMinutes = 60,
                            Price = 160m,
                            ServiceName = "Masaż klasyczny"
                        },
                        new
                        {
                            Id = 27,
                            BranchId = 6,
                            CompanyId = 6,
                            Description = "Intensywny masaż dla osób aktywnych",
                            DurationMinutes = 60,
                            Price = 190m,
                            ServiceName = "Masaż sportowy"
                        },
                        new
                        {
                            Id = 28,
                            BranchId = 6,
                            CompanyId = 6,
                            Description = "Skoncentrowany masaż na odcinku lędźwiowym i szyjnym",
                            DurationMinutes = 45,
                            Price = 210m,
                            ServiceName = "Masaż leczniczy kręgosłupa"
                        },
                        new
                        {
                            Id = 29,
                            BranchId = 6,
                            CompanyId = 6,
                            Description = "Zabieg wspierający układ limfatyczny",
                            DurationMinutes = 60,
                            Price = 200m,
                            ServiceName = "Drenaż limfatyczny"
                        },
                        new
                        {
                            Id = 30,
                            BranchId = 6,
                            CompanyId = 6,
                            Description = "Relaksacyjny masaż z użyciem świecy",
                            DurationMinutes = 75,
                            Price = 220m,
                            ServiceName = "Masaż świecą"
                        },
                        new
                        {
                            Id = 31,
                            BranchId = 7,
                            CompanyId = 7,
                            Description = "Strzyżenie męskie z dowolną kawą w cenie",
                            DurationMinutes = 45,
                            Price = 85m,
                            ServiceName = "Strzyżenie z kawą"
                        },
                        new
                        {
                            Id = 32,
                            BranchId = 7,
                            CompanyId = 7,
                            Description = "Modelowanie brody z pielęgnacją",
                            DurationMinutes = 35,
                            Price = 70m,
                            ServiceName = "Stylizacja brody"
                        },
                        new
                        {
                            Id = 33,
                            BranchId = 7,
                            CompanyId = 7,
                            Description = "Strzyżenie, broda oraz kawa speciality",
                            DurationMinutes = 75,
                            Price = 140m,
                            ServiceName = "Pakiet premium"
                        },
                        new
                        {
                            Id = 34,
                            BranchId = 7,
                            CompanyId = 7,
                            Description = "Szybkie strzyżenie dla zabieganych",
                            DurationMinutes = 25,
                            Price = 60m,
                            ServiceName = "Strzyżenie ekspres"
                        },
                        new
                        {
                            Id = 35,
                            BranchId = 7,
                            CompanyId = 7,
                            Description = "Mycie i odżywka do włosów",
                            DurationMinutes = 20,
                            Price = 40m,
                            ServiceName = "Pielęgnacja włosów"
                        },
                        new
                        {
                            Id = 36,
                            BranchId = 8,
                            CompanyId = 8,
                            Description = "Zabieg mezoterapii skóry twarzy",
                            DurationMinutes = 90,
                            Price = 450m,
                            ServiceName = "Mezoterapia igłowa"
                        },
                        new
                        {
                            Id = 37,
                            BranchId = 8,
                            CompanyId = 8,
                            Description = "Zabieg złuszczający dobrany do typu skóry",
                            DurationMinutes = 60,
                            Price = 280m,
                            ServiceName = "Peeling chemiczny"
                        },
                        new
                        {
                            Id = 38,
                            BranchId = 8,
                            CompanyId = 8,
                            Description = "Zaawansowany zabieg przeciwstarzeniowy",
                            DurationMinutes = 75,
                            Price = 400m,
                            ServiceName = "Zabieg anti-aging"
                        },
                        new
                        {
                            Id = 39,
                            BranchId = 8,
                            CompanyId = 8,
                            Description = "Analiza skóry i plan pielęgnacji",
                            DurationMinutes = 45,
                            Price = 150m,
                            ServiceName = "Konsultacja kosmetologiczna"
                        },
                        new
                        {
                            Id = 40,
                            BranchId = 8,
                            CompanyId = 8,
                            Description = "Nowoczesne oczyszczanie skóry",
                            DurationMinutes = 70,
                            Price = 320m,
                            ServiceName = "Oczyszczanie wodorowe"
                        },
                        new
                        {
                            Id = 41,
                            BranchId = 9,
                            CompanyId = 9,
                            Description = "Nowoczesne cięcie dopasowane do stylu",
                            DurationMinutes = 40,
                            Price = 75m,
                            ServiceName = "Strzyżenie miejskie"
                        },
                        new
                        {
                            Id = 42,
                            BranchId = 9,
                            CompanyId = 9,
                            Description = "Rozjaśnianie i koloryzacja techniką balayage",
                            DurationMinutes = 150,
                            Price = 260m,
                            ServiceName = "Balayage"
                        },
                        new
                        {
                            Id = 43,
                            BranchId = 9,
                            CompanyId = 9,
                            Description = "Wygładzanie włosów keratyną",
                            DurationMinutes = 180,
                            Price = 350m,
                            ServiceName = "Prostowanie keratynowe"
                        },
                        new
                        {
                            Id = 44,
                            BranchId = 9,
                            CompanyId = 9,
                            Description = "Strzyżenie dla dzieci",
                            DurationMinutes = 30,
                            Price = 55m,
                            ServiceName = "Strzyżenie dziecięce"
                        },
                        new
                        {
                            Id = 45,
                            BranchId = 9,
                            CompanyId = 9,
                            Description = "Fryzura na wesele lub imprezę",
                            DurationMinutes = 90,
                            Price = 190m,
                            ServiceName = "Upięcie okolicznościowe"
                        },
                        new
                        {
                            Id = 51,
                            BranchId = 11,
                            CompanyId = 11,
                            Description = "Tradycyjne strzyżenie męskie z precyzją",
                            DurationMinutes = 30,
                            Price = 55m,
                            ServiceName = "Strzyżenie męskie klasyczne"
                        },
                        new
                        {
                            Id = 52,
                            BranchId = 11,
                            CompanyId = 11,
                            Description = "Modelowanie i stylizacja brody",
                            DurationMinutes = 25,
                            Price = 65m,
                            ServiceName = "Strzyżenie brody"
                        },
                        new
                        {
                            Id = 53,
                            BranchId = 11,
                            CompanyId = 11,
                            Description = "Klasyczne golenie z gorącym ręcznikiem",
                            DurationMinutes = 40,
                            Price = 75m,
                            ServiceName = "Golenie brzytwą tradycyjne"
                        },
                        new
                        {
                            Id = 54,
                            BranchId = 11,
                            CompanyId = 11,
                            Description = "Kompleksowa pielęgnacja brody",
                            DurationMinutes = 60,
                            Price = 120m,
                            ServiceName = "Pakiet premium broda"
                        },
                        new
                        {
                            Id = 55,
                            BranchId = 11,
                            CompanyId = 11,
                            Description = "Nowoczesne strzyżenie dla młodych mężczyzn",
                            DurationMinutes = 25,
                            Price = 45m,
                            ServiceName = "Strzyżenie młodzieżowe"
                        },
                        new
                        {
                            Id = 56,
                            BranchId = 12,
                            CompanyId = 12,
                            Description = "Profesjonalne strzyżenie z modelowaniem",
                            DurationMinutes = 60,
                            Price = 85m,
                            ServiceName = "Strzyżenie damskie"
                        },
                        new
                        {
                            Id = 57,
                            BranchId = 12,
                            CompanyId = 12,
                            Description = "Farbowanie z konsultacją kolorystyczną",
                            DurationMinutes = 120,
                            Price = 220m,
                            ServiceName = "Koloryzacja włosów"
                        },
                        new
                        {
                            Id = 58,
                            BranchId = 12,
                            CompanyId = 12,
                            Description = "Relaksacyjny masaż skóry głowy",
                            DurationMinutes = 30,
                            Price = 60m,
                            ServiceName = "Masaż głowy"
                        },
                        new
                        {
                            Id = 59,
                            BranchId = 12,
                            CompanyId = 12,
                            Description = "Intensywna regeneracja włosów",
                            DurationMinutes = 90,
                            Price = 160m,
                            ServiceName = "Zabieg regenerujący"
                        },
                        new
                        {
                            Id = 60,
                            BranchId = 12,
                            CompanyId = 12,
                            Description = "Elegancka fryzura ślubna",
                            DurationMinutes = 120,
                            Price = 280m,
                            ServiceName = "Upięcie ślubne"
                        });
                });

            modelBuilder.Entity("ReservationService.Models.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SlotEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SlotStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StaffId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("BranchId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("CompanyId", "BranchId", "SlotStart", "SlotEnd");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("ReservationService.Models.Appointment", b =>
                {
                    b.HasOne("ReservationService.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationService.Models.Company", "Company")
                        .WithMany("Appointments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationService.Models.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Company");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ReservationService.Models.Branch", b =>
                {
                    b.HasOne("ReservationService.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ReservationService.Models.BranchReview", b =>
                {
                    b.HasOne("ReservationService.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationService.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationService.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Branch");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ReservationService.Models.Schedule", b =>
                {
                    b.HasOne("ReservationService.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationService.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationService.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Company");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ReservationService.Models.Service", b =>
                {
                    b.HasOne("ReservationService.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationService.Models.Company", "Company")
                        .WithMany("Services")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ReservationService.Models.TimeSlot", b =>
                {
                    b.HasOne("ReservationService.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReservationService.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationService.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationService.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Branch");

                    b.Navigation("Company");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ReservationService.Models.Company", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("ReservationService.Models.Service", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
