using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using NotificationService.Data;
using NotificationService.Hubs;
using NotificationService.Models;
using NotificationService.Services;
using System.Text;

var builder = WebApplication.CreateBuilder(args);

// Pobranie connection string
var connectionString = builder.Configuration.GetConnectionString("NotificationConnection")
                      ?? Environment.GetEnvironmentVariable("ConnectionStrings__NotificationConnection")
                      ?? throw new InvalidOperationException("Connection string 'NotificationConnection' not found.");

// Konfiguracja DbContext z PostgreSQL
builder.Services.AddDbContext<NotificationDbContext>(options =>
    options.UseNpgsql(connectionString));

// Rejestracja serwisów
builder.Services.Configure<EmailSettings>(builder.Configuration.GetSection("EmailSettings"));
builder.Services.AddSingleton<SmsInboxStore>();
builder.Services.AddScoped<INotificationSender, NotificationSender>();
builder.Services.AddHostedService<RabbitMQConsumer>();
builder.Services.AddHttpClient();

// Dodanie kontrolerów
builder.Services.AddControllers();

// Dodanie SignalR
builder.Services.AddSignalR();

// JWT Authentication
var jwtSection = builder.Configuration.GetSection("JwtSettings");
var secretKey = jwtSection["SecretKey"]
               ?? throw new InvalidOperationException("JwtSettings:SecretKey is not configured.");

var issuer = jwtSection["Issuer"]
             ?? throw new InvalidOperationException("JwtSettings:Issuer is not configured.");

var audience = jwtSection["Audience"]
               ?? throw new InvalidOperationException("JwtSettings:Audience is not configured.");

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.RequireHttpsMetadata = false;
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = issuer,
            ValidAudience = audience,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(secretKey)),
            ClockSkew = TimeSpan.Zero
        };

        options.Events = new JwtBearerEvents
        {
            OnMessageReceived = context =>
            {
                var accessToken = context.Request.Query["access_token"].ToString();
                var path = context.HttpContext.Request.Path;

                if (!string.IsNullOrWhiteSpace(accessToken)
                    && path.StartsWithSegments("/notificationHub"))
                {
                    context.Token = accessToken;
                }

                return Task.CompletedTask;
            }
        };
    });

builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("CompanyManagerOrOwnerOrAdmin", policy =>
        policy.RequireAssertion(ctx =>
            ctx.User.IsInRole("Admin")
            || ctx.User.HasClaim("CompanyRole", "Owner")
            || ctx.User.HasClaim("CompanyRole", "Manager")));
});

// Dodanie CORS
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        policy.WithOrigins("http://localhost:3000", "http://localhost:5173")
              .AllowAnyMethod()
              .AllowAnyHeader()
              .AllowCredentials(); // Ważne dla SignalR
    });
});

// Swagger
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Automatyczna migracja bazy danych z retry logic
using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<NotificationDbContext>();
    var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();

    var maxRetryCount = 10;
    var delay = TimeSpan.FromSeconds(3);

    for (int retry = 0; retry < maxRetryCount; retry++)
    {
        try
        {
            logger.LogInformation("Initializing NotificationDB... (attempt {Attempt}/{Max})", retry + 1, maxRetryCount);
            var migrations = dbContext.Database.GetMigrations().ToList();
            if (migrations.Count == 0)
            {
                logger.LogWarning("No EF Core migrations were found for NotificationDB. Falling back to EnsureCreated(). Generate an initial migration to use Database.Migrate().");
                dbContext.Database.EnsureCreated();
            }
            else
            {
                dbContext.Database.Migrate();
            }

            try
            {
                dbContext.Database.ExecuteSqlRaw(
                    "CREATE TABLE IF NOT EXISTS \"ProcessedMessages\" (\"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"DedupeKey\" text NOT NULL, \"MessageId\" text NULL, \"RoutingKey\" text NOT NULL, \"BodyHash\" text NOT NULL, \"ProcessedAt\" timestamp without time zone NOT NULL);");
                dbContext.Database.ExecuteSqlRaw(
                    "CREATE UNIQUE INDEX IF NOT EXISTS \"IX_ProcessedMessages_DedupeKey\" ON \"ProcessedMessages\" (\"DedupeKey\");");

                dbContext.Database.ExecuteSqlRaw(
                    "ALTER TABLE IF EXISTS \"NotificationTemplates\" ADD COLUMN IF NOT EXISTS \"Channel\" integer NOT NULL DEFAULT 0;");
                dbContext.Database.ExecuteSqlRaw(
                    "CREATE INDEX IF NOT EXISTS \"IX_NotificationTemplates_Type_Channel\" ON \"NotificationTemplates\" (\"Type\", \"Channel\");");

                dbContext.Database.ExecuteSqlRaw(
                    "DELETE FROM \"NotificationTemplates\" a USING \"NotificationTemplates\" b WHERE a.\"Id\" < b.\"Id\" AND a.\"Type\" = b.\"Type\" AND a.\"Channel\" = b.\"Channel\";");
                dbContext.Database.ExecuteSqlRaw(
                    "CREATE UNIQUE INDEX IF NOT EXISTS \"UX_NotificationTemplates_Type_Channel\" ON \"NotificationTemplates\" (\"Type\", \"Channel\");");
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "Failed to ensure ProcessedMessages schema.");
            }

            try
            {
                var existing = dbContext.NotificationTemplates
                    .AsNoTracking()
                    .Select(t => new { t.Type, t.Channel })
                    .ToList();

                var existingKeys = new HashSet<string>(
                    existing.Select(x => $"{(int)x.Type}:{(int)x.Channel}"),
                    StringComparer.Ordinal);

                var defaults = new List<NotificationTemplate>
                {
                    new NotificationTemplate
                    {
                        Name = "AppointmentConfirmation (SMS)",
                        Type = NotificationType.AppointmentConfirmation,
                        Channel = NotificationChannel.SMS,
                        Subject = "Rezerwacja",
                        Body = "Potwierdzono: {{serviceName}} | {{companyAddressShort}} | {{appointmentShort}}",
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow
                    },
                    new NotificationTemplate
                    {
                        Name = "AppointmentConfirmation (InApp)",
                        Type = NotificationType.AppointmentConfirmation,
                        Channel = NotificationChannel.InApp,
                        Subject = "Potwierdzenie rezerwacji",
                        Body = "Potwierdzono: {{serviceName}} | {{companyAddressShort}} | {{appointmentShort}}",
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow
                    },
                    new NotificationTemplate
                    {
                        Name = "AppointmentCancellation (SMS)",
                        Type = NotificationType.AppointmentCancellation,
                        Channel = NotificationChannel.SMS,
                        Subject = "Rezerwacja",
                        Body = "Anulowano: {{serviceName}} | {{companyAddressShort}} | {{appointmentShort}}",
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow
                    },
                    new NotificationTemplate
                    {
                        Name = "AppointmentCancellation (InApp)",
                        Type = NotificationType.AppointmentCancellation,
                        Channel = NotificationChannel.InApp,
                        Subject = "Anulowanie rezerwacji",
                        Body = "Anulowano: {{serviceName}} | {{companyAddressShort}} | {{appointmentShort}}",
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow
                    },
                    new NotificationTemplate
                    {
                        Name = "AppointmentReminder (SMS)",
                        Type = NotificationType.AppointmentReminder,
                        Channel = NotificationChannel.SMS,
                        Subject = "Przypomnienie",
                        Body = "Przypomnienie: {{serviceName}} | {{companyAddressShort}} | {{appointmentShort}}",
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow
                    },
                    new NotificationTemplate
                    {
                        Name = "AppointmentReminder (InApp)",
                        Type = NotificationType.AppointmentReminder,
                        Channel = NotificationChannel.InApp,
                        Subject = "Przypomnienie o wizycie",
                        Body = "Przypomnienie: {{serviceName}} | {{companyAddressShort}} | {{appointmentShort}}",
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow
                    }
                };

                foreach (var t in defaults)
                {
                    var key = $"{(int)t.Type}:{(int)t.Channel}";
                    if (existingKeys.Contains(key))
                    {
                        continue;
                    }

                    dbContext.NotificationTemplates.Add(t);
                }

                dbContext.SaveChanges();
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "Failed to seed default notification templates.");
            }

            logger.LogInformation("NotificationDB is ready!");
            break;
        }
        catch (Exception ex)
        {
            if (retry == maxRetryCount - 1)
            {
                logger.LogError(ex, "Failed to initialize NotificationDB after all retries.");
                throw;
            }

            logger.LogWarning("Failed to connect to database. Retrying in {DelaySeconds} seconds... ({Attempt}/{Max})", delay.TotalSeconds, retry + 1, maxRetryCount);
            Thread.Sleep(delay);
        }
    }
}

// Konfiguracja pipeline
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseCors("AllowFrontend");

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

// MapHub dla SignalR
app.MapHub<NotificationHub>("/notificationHub");

// Podstawowy endpoint healthcheck
app.MapGet("/health", () => Results.Ok(new { status = "healthy", service = "NotificationService" }))
   .WithName("HealthCheck");

Console.WriteLine("🔔 NotificationService uruchomiony na porcie 5003");

app.Run();
